### ISSUE TITLE
Crashes within a second of opening

### ISSUE THREAD

**Issue by revelt** [alexindigo/ndash#4]
I'm on iPhone 7 and this app crashes within a second of opening. It used to crash more rarely but recently it's unusable.

It must be some API not responding (or changed since) and algorithm is not anticipating that.

If you can, please look into fixing this app. It's really useful and I'd be happy to pay for a such thing (working-one).

But otherwise, good job, please don't abandon this app.

**Comment by alexindigo** [comment]
Hey,

Thanks for the report (and for the nice words).

Looks like it's happening across the devices, getting similar thing on android as well.
Probably related to npm api changes, will investigate.

**Comment by alexindigo** [comment]
npms.io search is down, looks like the reason. Twitted them :)

**Comment by revelt** [comment]
what about http://npmsearch.com/ , maybe they have an API?

**Comment by alexindigo** [comment]
When I researched different APIs for the project npms.io was the most st stable and robust. Don't remember what was the verdict for npmsearch.
And they're back: https://twitter.com/npms_io/status/908361266443509760
